import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Home, Articles} from "../components/sections";
import Career from "src/components/sections/Career";
import About from "src/components/About";

import styled from "styled-components";
const Wrapper = styled.div`
  max-width: 1440px;
`;
export default function Index() {
  return (
    <Wrapper>
      <Head>
        <title>Rustamxon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home />
      <Career />
      <Articles />
      <About/>
      <Footer />
    </Wrapper>
  );
}
